
FOURSQUARE_API_CLIENT_ID = "TXRYPUX0100TCJG0R3ZVLNKA0YFHCVGJDCDRUMI4EY25TEU0"
FOURSQUARE_API_CLIENT_SECRET = "IPI0ESJWVZSBCJZINMVSLGUWPNAZEE2F2DCSOPEYD2KCQ5PA"


METWIT_CLIENT_ID = ""
METWIT_CLIENT_SECRET = ""